version: '3.8'

services:
  tournament-service:
    build:
      context: ./services/tournament-service  # Path to your tournament service folder
      dockerfile: tournament_service.dockerfile
    ports:
      - "5002:5002"  
    environment:
      - FLASK_ENV=development
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json  # Mount the Firebase credentials

  teams-service:
    build:
      context: ./services/teams-service  # Path to your teams service folder
      dockerfile: teams_service.dockerfile
    ports:
      - "5003:5003" 
    environment:
      - FLASK_ENV=development
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json  # Mount the Firebase credentials

  match-service:
    build:
      context: ./services/match-service  # Path to your match service folder
      dockerfile: match_service.dockerfile
    ports:
      - "5004:5004"  
    environment:
      - FLASK_ENV=development
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json  # Mount the Firebase credentials
  

  player-service:
    build:
      context: ./services/player-service  # Path to your player service folder
      dockerfile: player_service.dockerfile
    ports:
      - "5001:5001" 
    environment:
      - FLASK_ENV=development
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json  # Mount the Firebase credentials
    

  schedule-service:
    build:
      context: ./services/schedule-service  # Path to your schedule service folder
      dockerfile: schedule_service.dockerfile
    ports:
      - "5005:5005"  
    environment:
      - FLASK_ENV=development
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json  # Mount the Firebase credentials


  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  composite_service:
    build:
      context: ./composite-service/join-team-service
      dockerfile: composite_service.dockerfile 
    ports:
      - "5006:5006"
    depends_on:
      - rabbitmq

  join_logger:
    build:
      context: ./join-logger
      dockerfile: join_logger.dockerfile
    depends_on:
      - rabbitmq
    
  notification-service:
    build:
      context: ./services/notification-service
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./services/notification-service/.env
  
  handle-dispute-service:
    build:
      context: ./composite-service/handle-dispute-service
      dockerfile: handle_dispute_service.dockerfile
    ports:
      - "5008:5008"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json
   


  finalize-match-outcome-service:
    build:
      context: ./composite-service/finalize-match-outcome-service
      dockerfile: finalize_match_outcome_service.dockerfile
    ports:
      - "5009:5009"  
    depends_on:
      - match-service
      - tournament-service


